### ISSUE TITLE
Port ListView Header Behaviors

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Windows#112]
```[tasklist]
### Tasks
- [x] Needs rest of Animation package to be ported??? (May be there... not sure)
- [x] Remove 'Behaviors.Animations' package and move to Behaviors (add dependency)
- [x] Port Header behavior code itself
```

**Comment by michael-hawker** [comment]
See PR for more details. This is pretty much ready to go. Was able to bring these over and do a lot of clean-up on them to make them easier to maintain and share a bunch of common code between the three of them.

It also enables them to work great for our new DataTable scenarios in the future, so it's going to be pretty awesome.

Also, enabled other potential future scenarios, but those need more baking, so maybe something we can investigate if needed more in the future. It's actually kind of similar to some of the TransitionHelper scenarios I think from the Store, so that may just be a better route to show that scenario with?
