### ISSUE TITLE
Add Better Docs/Samples for Animations component

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Windows#149]
We should have the following for the Animations package:

```[tasklist]
### Tasks
- [ ] Port existing AnimationSet/ImplicitAnimationSet/AnimationBuilder/Connected/ItemsReorderAnimations docs
- [ ] Better introductory guidance on getting started with Animations in general (central 'Animations' page) - how are these things connected, what types of animations (implicit, explicit, connected, etc...)
- [ ] Ensure there's some basic samples on simple animation sets (Explicit) - no extra frills
- [ ] Bring over existing Connected Animations sample
- [ ] Bring over existing ItemsReorderAnimation sample
- [ ] Bring over Scale animation sample
```
