### ISSUE TITLE
Sample App in Store

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Windows#195]
This issue is tracking things we need to get done to ship the sample app in the store.
```[tasklist]
### Tasks
- [x] Go through categories
- [ ] https://github.com/CommunityToolkit/Windows/issues/197
- [ ] Store Telemetry like we had in previous app
- [ ] https://github.com/CommunityToolkit/Tooling-Windows-Submodule/issues/100
- [ ] https://github.com/CommunityToolkit/Tooling-Windows-Submodule/issues/105
- [ ] https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/103
- [x] Documentation Pass - for instance Effects still has 'TODO' in it and no Icon
- [x] Link to Repo https://aka.ms/toolkit/windows and Docs https://aka.ms/toolkit/docs (general?) in Settings page
- [x] Extra gap between titlebar and top of page ~16px? (UWP)
- [ ] https://github.com/CommunityToolkit/Windows/pull/180
```

**Comment by michael-hawker** [comment]
Need to check on UWP, but noticed on WASM some icons are missing for some components:

![image](https://github.com/CommunityToolkit/Windows/assets/24302614/5503dcaa-db86-409e-9a2e-d46d603eb560)

**Comment by michael-hawker** [comment]
Main issue right now is I haven't been able to build the UWP app head in Release mode and publish a package for it. Visual Studio keeps hanging. And building on the command line seems to be throwing other random errors for WASM or WinAppSDK heads. Not sure how to workaround this yet... This is our main ship blocker.

@niels9001 can you maybe try building in release mode and then using the right-click publish create app package and see how it works on your machine?

**Comment by michael-hawker** [comment]
We'll be good here, I'll put the Store SDK APIs in locally for the final build for now until we figure out why #206 kills the CI.

Think #214 covers rest of main issues.

We'll be replacing the existing app in the store, seems like things should go smoothly for that?

Going to open an issue as Markdown Tables don't render and we didn't add the DocFX extension from the old Sample App... We'll want to probably just bring those things forward to test on the new version in Labs: https://github.com/CommunityToolkit/Labs-Windows/pull/480
