### ISSUE TITLE
Port Converters

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Windows#2]
## TODO

```[tasklist]
### Base Porting Checklist
- [x] Update namespace (to `CommunityToolkit.WinUI.Converters`)
- [ ] Merge differences from UWP main to WinAppSDK, Uno Platform fork
- [x] Import original doc or setup new doc
- [ ] Needs a refresh/update, and probably split
- [ ] https://github.com/CommunityToolkit/Windows/issues/133
- [ ] Brought over existing unit tests from main repo (**did not** compare or merge with WinUI branch **nor** update to use our helpers)
- [x] All brought over tests pass for UWP/WinAppSDK
- [ ] https://github.com/CommunityToolkit/Windows/issues/132
- [ ] Support for WASM via Uno Platform (Had trouble testing due to https://github.com/CommunityToolkit/Tooling-Windows-Submodule/issues/24)
- [ ] ResourceNameToResourceStringConverter definitely needs to be compared
- [x] `StringFormatConverter` from first sample worked fine!
```

```[tasklist]
## Converters
- [x] BoolNegationConverter
- [x] BoolToObjectConverter
- [x] BoolToVisibilityConverter
- [x] CollectionVisibilityConverter
- [x] ColorToDisplayNameConverter
- [x] DoubleToObjectConverter
- [x] DoubleToVisibilityConverter
- [x] EmptyCollectionToObjectConverter
- [x] EmptyObjectToObjectConverter
- [x] EmptyStringToObjectConverter
- [x] FileSizeToFriendlyStringConverter
- [x] FormatStringConverter
- [x] ResourceNameTOResourceStringConverter
- [x] StringFormatConverter
- [x] StringVisibilityConverter
- [x] TaskResultConverter
- [x] TypeToObjectConverter
- [x] VisibilityToBoolConverter
```

## Notable Changes

- Changed `FormatStringConverter` to `IFormattableToStringConverter` to differentiate from `StringFormatConverter` (too confusing to have such a similar name)

```[tasklist]
## Prerequisites
- [ ] https://github.com/microsoft/microsoft-ui-xaml/issues/8287
```

```[tasklist]
## Future Improvements
- [ ] P2: Central x:Bind helper class that leverages shared logic of converters?
```
