### ISSUE TITLE
Port Animations Package

### ISSUE THREAD

**Issue by michael-hawker** [CommunityToolkit/Windows#25]
## TODO
May need #17 first, #7 will need the extra animation support and dependency after as well. (i.e. keep similar dependency tree that we had in 7.0, behaviors depends on animations)

```[tasklist]
### Base Porting Checklist
- [x] Component name (to `CommunityToolkit.WinUI.Animations`)
- [x] Merge differences from UWP main to WinAppSDK / Uno forks
- [ ] Support for WASM via Uno Platform
- [ ] Improve Samples
- [ ] All brought over tests pass for UWP/WinAppSDK
```

```[tasklist]
### Known Issues
```

```[tasklist]
### Improvements
```
