### ISSUE TITLE
Port Triggers

### ISSUE THREAD

**Issue by niels9001** [CommunityToolkit/Windows#4]
## TODO

```[tasklist]
### Base Porting Checklist
- [x] Update namespace (to `CommunityToolkit.WinUI.Triggers`)
- [x] Merge differences from UWP main to WinAppSDK / Uno forks
- [x] Import original doc or setup new doc
  - [ ] Needs a refresh/update, and probably split
- [x] Samples
- [ ] #111
  - [ ] All brought over tests pass for UWP/WinAppSDK
  - [ ] Add more tests for other converters not covered? (or at least well-used ones)
- [ ] https://github.com/CommunityToolkit/Windows/issues/110
```

```[tasklist]
### Triggers
- [x] CompareStateTrigger
- [x] ControlSizeTrigger
- [ ] FullscreenModeStateTrigger (missing APIs WASDK)
- [x] IsEqualStateTrigger
- [x] IsNotEqualStateTrigger
- [x] IsNullOrEmptyStateTrigger
- [x] NetworkConnectionStateTrigger
- [x] RegexStateTrigger
- [x] UserHandPreferenceStateTrigger
- [ ] UserInteractionModeStateTrigger (missing APIs WASDK)
```

```[tasklist]
## Notable Changes
```

```[tasklist]
## Future Improvements

```

```[tasklist]
## Dependencies
- [x] DispatcherQueueExtensions.cs
- [ ] #22
```
