### ISSUE TITLE
Port (Framework)Extensions

### ISSUE THREAD

**Issue by niels9001** [CommunityToolkit/Windows#6]
## TODO

```[tasklist]
### Base Porting Checklist
- [x] Component/package name (`CommunityToolkit.WinUI.Extensions`)
- [x] Namespace `CommunityToolkit.WinUI`
- [x] Merge differences from UWP main to WinAppSDK / Uno forks
- [x] Import original doc or setup new doc
- [ ] Needs a refresh/update, and probably split
- [x] Samples
- [ ] Tests
- [ ] All brought over tests pass for UWP/WinAppSDK
- [ ] https://github.com/CommunityToolkit/Windows/issues/134
- [x] Support for WASM via Uno Platform
```

```[tasklist]
### Extensions
- [x] FrameworkElementExtensions
- [x] ListViewExtensions
- [x] BitmapIconExtension
- [x] BitmapIconSourceExtension
- [x] EnumValuesExtension
- [x] FontIconExtension
- [x] FontIcoNSourceExtension
- [x] NullableBoolExtension
- [x] OnDeviceExtension
- [x] SymbolIconExtension
- [x] SymbolIconSourceExtension
- [x] MatrixExtensions
- [x] RectExtensions
- [x] RotateTransformExtensions
- [x] SkewTransformExtensions
- [x] TranslateTransformExtensions
- [x] ScrollViewExtensions
- [x] TextBoxExtensions
- [ ] TitleBarExtensions (Blocked: Missing WinUI APIs)
- [ ] ElementExtensions (Blocked: Missing WinUI APIs)
- [ ] ApplicationViewExtensions (Blocked: Missing WinUI APIs)
- [ ] WebViewExtensions (Deprecate in favor of `WebView2`)
- [x] PointExtensions
- [x] RectExtensions
- [x] SizeExtensions
- [x] StringExtensions
- [x] HyperlinkExtensions
- [x] DependencyObjectExtensions
- [x] DispatcherQueueExtensions
```

```[tasklist]
### Known issues
```

```[tasklist]
### Future improvements
```

```[tasklist]
## Notable Changes
- [ ] For FrameworkExtensions, look at https://github.com/CommunityToolkit/Labs-Windows/blob/main/components/SegmentedControl/src/Helpers/FrameworkElementExtensions.cs. Some changes were made that to trigger the extension upon loading.
```

**Comment by hoshiizumiya** [comment]
https://github.com/CommunityToolkit/Windows/blob/main/components/Extensions/src/ScrollViewer/ScrollViewerExtensions.Properties.cs
For ScrollViewerExtensions.EnableMiddleClickScrolling, it doesn't exist.
<img width="3840" height="2064" alt="Image" src="https://github.com/user-attachments/assets/6cb99810-80a0-4227-9ffe-acac1a80b421" />
