### ISSUE TITLE
Port Behaviors

### ISSUE THREAD

**Issue by niels9001** [CommunityToolkit/Windows#7]
## TODO

```[tasklist]
### Base Porting Checklist
- [x] Component name (to `CommunityToolkit.WinUI.Behaviors`)
- [x] Merge differences from UWP main to
- [x] WinAppSDK
- [x] Uno Platform fork
- [x] Support for WASM via Uno Platform
- [ ] Do we split up docs into individual behaviors?
- [ ] Improve Samples
- [ ] All brought over tests pass for UWP/WinAppSDK
```

```[tasklist]
### Known Issues
- [ ] Add more tests for other behaviors not covered
- [ ] `AutoSelectBehavior` not working on WinAppSDK
- [ ] `AutoSelectBehavior` not working when clicking in/on the textbox, only with keyboard focus (I think the new platform styles don't show selection when the control doesn't have focus, so this may be related compared to how it used to work?)
- [ ] Bit confused by `FocusBehavior` and what it enables, maybe we can improve docs/samples later
- [ ] The `KeyDownTriggerBehavior` not working on WASM as you mentioned
- [ ] Doesn't look like the `IsAlwaysOn` properly unregisters for the `ViewportBehavior` on WASM
```

```[tasklist]
### Improvements
- [ ] Add the NavigateToUri behavior from Labs (for Buttons)? https://github.com/CommunityToolkit/Labs-Windows/blob/main/tooling/CommunityToolkit.App.Shared/Behaviors/NavigateToUriAction.cs
```

## Notable Changes

- Missing Animation related Behaviors until brought over.

**Comment by michael-hawker** [comment]
@niels9001 did we not port the header behaviors like quick return and sticky and such?
